# Make executable with chmod +x <<filename.sh>>
echo "What is your github username?"
read USERNAME

if gh auth status;  then 
  echo 'already logged into github'
else 
  gh auth login
fi

if [ -d "./bitcointranscripts/" ]; then

  cd bitcointranscripts

else
  gh repo fork bitcointranscripts/bitcointranscripts --clone 

  cd bitcointranscripts
fi

git_branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$git_branch" != "master" ]; then
  git checkout master
fi

gh repo sync --branch master 


if [ "git branch --list ${3}" ]; then
  git checkout "${3}"    
else 
  git checkout -b "${3}"
fi


if [ ! -d "./${2}" ]; then 
  mkdir -p "${2}"
fi

IFS=/ read -a dirs <<< ${2}
IFS=' ' read -a sub_dirs <<< ${dirs[0]}

cd ${sub_dirs[0]}
if [ ! -f ./_index.md ]; then
  echo -e "---\ntitle: ${sub_dirs[0]}\n---\n\n{{< childpages >}}" >> _index.md
fi

cd ${sub_dirs[1]}

if [ ! -f ./_index.md ]; then
  echo -e "---\ntitle: ${dirs[0]}\n---\n\n{{< childpages >}}" >> _index.md
fi
 
cd ../..

mv "${1}" "./${2}"

git add . && git commit -m 'initial transcription using tstbtc tool'

gh repo set-default "${USERNAME}"/bitcointranscripts

gh pr create --base master --title "Autogenerated tstbtc: ${3}" --body "transcriber to bitcoin transcript for ${3}"

echo "Done"

